/* tslint:disable */
/* eslint-disable */
/**
 * juju Admin API
 * juju Admin API Restdocs
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ApiResponseBoolean
 */
export interface ApiResponseBoolean {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseBoolean
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseBoolean
     */
    'message': string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponseBoolean
     */
    'data'?: boolean;
    /**
     * 
     * @type {PageResponse}
     * @memberof ApiResponseBoolean
     */
    'pageResponse'?: PageResponse;
}
/**
 * 
 * @export
 * @interface ApiResponseGetPreSignedUrlResponse
 */
export interface ApiResponseGetPreSignedUrlResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseGetPreSignedUrlResponse
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseGetPreSignedUrlResponse
     */
    'message': string;
    /**
     * 
     * @type {GetPreSignedUrlResponse}
     * @memberof ApiResponseGetPreSignedUrlResponse
     */
    'data'?: GetPreSignedUrlResponse;
    /**
     * 
     * @type {PageResponse}
     * @memberof ApiResponseGetPreSignedUrlResponse
     */
    'pageResponse'?: PageResponse;
}
/**
 * 
 * @export
 * @interface ApiResponseListLong
 */
export interface ApiResponseListLong {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseListLong
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListLong
     */
    'message': string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ApiResponseListLong
     */
    'data'?: Array<number>;
    /**
     * 
     * @type {PageResponse}
     * @memberof ApiResponseListLong
     */
    'pageResponse'?: PageResponse;
}
/**
 * 
 * @export
 * @interface ApiResponseListProductColorResponse
 */
export interface ApiResponseListProductColorResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseListProductColorResponse
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListProductColorResponse
     */
    'message': string;
    /**
     * 
     * @type {Array<ProductColorResponse>}
     * @memberof ApiResponseListProductColorResponse
     */
    'data'?: Array<ProductColorResponse>;
    /**
     * 
     * @type {PageResponse}
     * @memberof ApiResponseListProductColorResponse
     */
    'pageResponse'?: PageResponse;
}
/**
 * 
 * @export
 * @interface ApiResponseListProductImageResponse
 */
export interface ApiResponseListProductImageResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseListProductImageResponse
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListProductImageResponse
     */
    'message': string;
    /**
     * 
     * @type {Array<ProductImageResponse>}
     * @memberof ApiResponseListProductImageResponse
     */
    'data'?: Array<ProductImageResponse>;
    /**
     * 
     * @type {PageResponse}
     * @memberof ApiResponseListProductImageResponse
     */
    'pageResponse'?: PageResponse;
}
/**
 * 
 * @export
 * @interface ApiResponseListProductMaterialResponse
 */
export interface ApiResponseListProductMaterialResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseListProductMaterialResponse
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListProductMaterialResponse
     */
    'message': string;
    /**
     * 
     * @type {Array<ProductMaterialResponse>}
     * @memberof ApiResponseListProductMaterialResponse
     */
    'data'?: Array<ProductMaterialResponse>;
    /**
     * 
     * @type {PageResponse}
     * @memberof ApiResponseListProductMaterialResponse
     */
    'pageResponse'?: PageResponse;
}
/**
 * 
 * @export
 * @interface ApiResponseListProductResponse
 */
export interface ApiResponseListProductResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseListProductResponse
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListProductResponse
     */
    'message': string;
    /**
     * 
     * @type {Array<ProductResponse>}
     * @memberof ApiResponseListProductResponse
     */
    'data'?: Array<ProductResponse>;
    /**
     * 
     * @type {PageResponse}
     * @memberof ApiResponseListProductResponse
     */
    'pageResponse'?: PageResponse;
}
/**
 * 
 * @export
 * @interface ApiResponseLong
 */
export interface ApiResponseLong {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseLong
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseLong
     */
    'message': string;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseLong
     */
    'data'?: number;
    /**
     * 
     * @type {PageResponse}
     * @memberof ApiResponseLong
     */
    'pageResponse'?: PageResponse;
}
/**
 * 
 * @export
 * @interface ChangePrimaryProductImageRequest
 */
export interface ChangePrimaryProductImageRequest {
    /**
     * 
     * @type {number}
     * @memberof ChangePrimaryProductImageRequest
     */
    'productId': number;
    /**
     * 
     * @type {number}
     * @memberof ChangePrimaryProductImageRequest
     */
    'primaryProductImageId': number;
}
/**
 * 
 * @export
 * @interface DeleteProductColorRequest
 */
export interface DeleteProductColorRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof DeleteProductColorRequest
     */
    'productColorIds': Array<number>;
}
/**
 * 
 * @export
 * @interface DeleteProductImageRequest
 */
export interface DeleteProductImageRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof DeleteProductImageRequest
     */
    'productImageIds': Array<number>;
}
/**
 * 
 * @export
 * @interface DeleteProductMaterialRequest
 */
export interface DeleteProductMaterialRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof DeleteProductMaterialRequest
     */
    'productMaterialIds': Array<number>;
}
/**
 * 
 * @export
 * @interface GetPreSignedUrlResponse
 */
export interface GetPreSignedUrlResponse {
    /**
     * 
     * @type {string}
     * @memberof GetPreSignedUrlResponse
     */
    'virtualImagePath': string;
    /**
     * 
     * @type {string}
     * @memberof GetPreSignedUrlResponse
     */
    'preSignedUrl': string;
}
/**
 * 
 * @export
 * @interface PageResponse
 */
export interface PageResponse {
    /**
     * 
     * @type {number}
     * @memberof PageResponse
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof PageResponse
     */
    'size': number;
    /**
     * 
     * @type {number}
     * @memberof PageResponse
     */
    'totalPageCount': number;
}
/**
 * 
 * @export
 * @interface ProductColorResponse
 */
export interface ProductColorResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductColorResponse
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof ProductColorResponse
     */
    'productId': number;
    /**
     * 
     * @type {string}
     * @memberof ProductColorResponse
     */
    'color': ProductColorResponseColorEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductColorResponse
     */
    'additionalPrice': number;
}

export const ProductColorResponseColorEnum = {
    Gold: 'GOLD',
    RoseGold: 'ROSE_GOLD',
    WhiteGold: 'WHITE_GOLD'
} as const;

export type ProductColorResponseColorEnum = typeof ProductColorResponseColorEnum[keyof typeof ProductColorResponseColorEnum];

/**
 * 
 * @export
 * @interface ProductImageResponse
 */
export interface ProductImageResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductImageResponse
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof ProductImageResponse
     */
    'productId': number;
    /**
     * 
     * @type {string}
     * @memberof ProductImageResponse
     */
    'imageUrl': string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductImageResponse
     */
    'isPrimary': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductImageResponse
     */
    'primary'?: boolean;
}
/**
 * 
 * @export
 * @interface ProductMaterialResponse
 */
export interface ProductMaterialResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductMaterialResponse
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof ProductMaterialResponse
     */
    'productId': number;
    /**
     * 
     * @type {string}
     * @memberof ProductMaterialResponse
     */
    'material': ProductMaterialResponseMaterialEnum;
    /**
     * 
     * @type {number}
     * @memberof ProductMaterialResponse
     */
    'additionalPrice': number;
}

export const ProductMaterialResponseMaterialEnum = {
    K10: 'K10',
    K14: 'K14',
    K18: 'K18',
    K22: 'K22',
    K24: 'K24',
    WhiteGold: 'WHITE_GOLD'
} as const;

export type ProductMaterialResponseMaterialEnum = typeof ProductMaterialResponseMaterialEnum[keyof typeof ProductMaterialResponseMaterialEnum];

/**
 * 
 * @export
 * @interface ProductResponse
 */
export interface ProductResponse {
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'productType': string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'productCode': string;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    'price': number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    'weightByMilliGram': number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'thumbnailImage'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductResponse
     */
    'isDiamond': boolean;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    'totalDiamondCaratX100': number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductResponse
     */
    'isDisplay': boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'updatedAt': string;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    'id': number;
}
/**
 * 
 * @export
 * @interface SaveBraceletAdditionalRequest
 */
export interface SaveBraceletAdditionalRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveBraceletAdditionalRequest
     */
    'maximumLength': number;
    /**
     * 
     * @type {number}
     * @memberof SaveBraceletAdditionalRequest
     */
    'minimumLength': number;
}
/**
 * 
 * @export
 * @interface SaveNecklaceAdditionalRequest
 */
export interface SaveNecklaceAdditionalRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveNecklaceAdditionalRequest
     */
    'maximumLength': number;
    /**
     * 
     * @type {number}
     * @memberof SaveNecklaceAdditionalRequest
     */
    'minimumLength': number;
}
/**
 * 
 * @export
 * @interface SaveProductColorInternalRequest
 */
export interface SaveProductColorInternalRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveProductColorInternalRequest
     */
    'color': SaveProductColorInternalRequestColorEnum;
    /**
     * 
     * @type {number}
     * @memberof SaveProductColorInternalRequest
     */
    'additionalPrice': number;
}

export const SaveProductColorInternalRequestColorEnum = {
    Gold: 'GOLD',
    RoseGold: 'ROSE_GOLD',
    WhiteGold: 'WHITE_GOLD'
} as const;

export type SaveProductColorInternalRequestColorEnum = typeof SaveProductColorInternalRequestColorEnum[keyof typeof SaveProductColorInternalRequestColorEnum];

/**
 * 
 * @export
 * @interface SaveProductColorRequest
 */
export interface SaveProductColorRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveProductColorRequest
     */
    'productId': number;
    /**
     * 
     * @type {Array<SaveProductColorInternalRequest>}
     * @memberof SaveProductColorRequest
     */
    'saveProductColorInternalRequests': Array<SaveProductColorInternalRequest>;
}
/**
 * 
 * @export
 * @interface SaveProductImageInternalRequest
 */
export interface SaveProductImageInternalRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveProductImageInternalRequest
     */
    'imageUrl': string;
    /**
     * 
     * @type {boolean}
     * @memberof SaveProductImageInternalRequest
     */
    'isPrimary': boolean;
}
/**
 * 
 * @export
 * @interface SaveProductImageRequest
 */
export interface SaveProductImageRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveProductImageRequest
     */
    'productId': number;
    /**
     * 
     * @type {Array<SaveProductImageInternalRequest>}
     * @memberof SaveProductImageRequest
     */
    'saveProductImageInternalRequests': Array<SaveProductImageInternalRequest>;
}
/**
 * 
 * @export
 * @interface SaveProductMaterialInternalRequest
 */
export interface SaveProductMaterialInternalRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveProductMaterialInternalRequest
     */
    'material': SaveProductMaterialInternalRequestMaterialEnum;
    /**
     * 
     * @type {number}
     * @memberof SaveProductMaterialInternalRequest
     */
    'additionalPrice': number;
}

export const SaveProductMaterialInternalRequestMaterialEnum = {
    K10: 'K10',
    K14: 'K14',
    K18: 'K18',
    K22: 'K22',
    K24: 'K24',
    WhiteGold: 'WHITE_GOLD'
} as const;

export type SaveProductMaterialInternalRequestMaterialEnum = typeof SaveProductMaterialInternalRequestMaterialEnum[keyof typeof SaveProductMaterialInternalRequestMaterialEnum];

/**
 * 
 * @export
 * @interface SaveProductMaterialRequest
 */
export interface SaveProductMaterialRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveProductMaterialRequest
     */
    'productId': number;
    /**
     * 
     * @type {Array<SaveProductMaterialInternalRequest>}
     * @memberof SaveProductMaterialRequest
     */
    'saveProductMaterialInternalRequest': Array<SaveProductMaterialInternalRequest>;
}
/**
 * 
 * @export
 * @interface SaveProductRequest
 */
export interface SaveProductRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveProductRequest
     */
    'productType': SaveProductRequestProductTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SaveProductRequest
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof SaveProductRequest
     */
    'price': number;
    /**
     * 
     * @type {number}
     * @memberof SaveProductRequest
     */
    'weightByMilliGram': number;
    /**
     * 
     * @type {string}
     * @memberof SaveProductRequest
     */
    'thumbnailImage': string;
    /**
     * 
     * @type {boolean}
     * @memberof SaveProductRequest
     */
    'isDiamond': boolean;
    /**
     * 
     * @type {number}
     * @memberof SaveProductRequest
     */
    'totalDiamondCaratX100': number;
    /**
     * 
     * @type {boolean}
     * @memberof SaveProductRequest
     */
    'isDisplay': boolean;
    /**
     * 
     * @type {SaveBraceletAdditionalRequest}
     * @memberof SaveProductRequest
     */
    'saveBraceletAdditionalRequest'?: SaveBraceletAdditionalRequest;
    /**
     * 
     * @type {SaveNecklaceAdditionalRequest}
     * @memberof SaveProductRequest
     */
    'saveNecklaceAdditionalRequest'?: SaveNecklaceAdditionalRequest;
}

export const SaveProductRequestProductTypeEnum = {
    Ring: 'RING',
    Necklace: 'NECKLACE',
    Earring: 'EARRING',
    Bracelet: 'BRACELET',
    Base: 'BASE'
} as const;

export type SaveProductRequestProductTypeEnum = typeof SaveProductRequestProductTypeEnum[keyof typeof SaveProductRequestProductTypeEnum];

/**
 * 
 * @export
 * @interface UpdateBraceletAdditionalRequest
 */
export interface UpdateBraceletAdditionalRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateBraceletAdditionalRequest
     */
    'maximumLength': number;
    /**
     * 
     * @type {number}
     * @memberof UpdateBraceletAdditionalRequest
     */
    'minimumLength': number;
}
/**
 * 
 * @export
 * @interface UpdateNecklaceAdditionalRequest
 */
export interface UpdateNecklaceAdditionalRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateNecklaceAdditionalRequest
     */
    'maximumLength': number;
    /**
     * 
     * @type {number}
     * @memberof UpdateNecklaceAdditionalRequest
     */
    'minimumLength': number;
}
/**
 * 
 * @export
 * @interface UpdateProductRequest
 */
export interface UpdateProductRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequest
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'productType': UpdateProductRequestProductTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequest
     */
    'price'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequest
     */
    'weightByMilliGram'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequest
     */
    'thumbnailImage'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProductRequest
     */
    'isDiamond'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequest
     */
    'totalDiamondCaratX100'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProductRequest
     */
    'isDisplay'?: boolean;
    /**
     * 
     * @type {UpdateBraceletAdditionalRequest}
     * @memberof UpdateProductRequest
     */
    'updateBraceletAdditionalRequest'?: UpdateBraceletAdditionalRequest;
    /**
     * 
     * @type {UpdateNecklaceAdditionalRequest}
     * @memberof UpdateProductRequest
     */
    'updateNecklaceAdditionalRequest'?: UpdateNecklaceAdditionalRequest;
}

export const UpdateProductRequestProductTypeEnum = {
    Ring: 'RING',
    Necklace: 'NECKLACE',
    Earring: 'EARRING',
    Bracelet: 'BRACELET',
    Base: 'BASE'
} as const;

export type UpdateProductRequestProductTypeEnum = typeof UpdateProductRequestProductTypeEnum[keyof typeof UpdateProductRequestProductTypeEnum];


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ChangePrimaryProductImageRequest} changePrimaryProductImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePrimaryImageOfProduct: async (changePrimaryProductImageRequest: ChangePrimaryProductImageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'changePrimaryProductImageRequest' is not null or undefined
            assertParamExists('changePrimaryImageOfProduct', 'changePrimaryProductImageRequest', changePrimaryProductImageRequest)
            const localVarPath = `/admin/api/v1/products/images/change-primary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changePrimaryProductImageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPreSignedUrl: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/api/v1/products/images/pre-signed-url`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DeleteProductColorRequest} deleteProductColorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProductColors: async (deleteProductColorRequest: DeleteProductColorRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteProductColorRequest' is not null or undefined
            assertParamExists('deleteProductColors', 'deleteProductColorRequest', deleteProductColorRequest)
            const localVarPath = `/admin/api/v1/products/colors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteProductColorRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DeleteProductImageRequest} deleteProductImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProductImages: async (deleteProductImageRequest: DeleteProductImageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteProductImageRequest' is not null or undefined
            assertParamExists('deleteProductImages', 'deleteProductImageRequest', deleteProductImageRequest)
            const localVarPath = `/admin/api/v1/products/images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteProductImageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DeleteProductMaterialRequest} deleteProductMaterialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProductMaterials: async (deleteProductMaterialRequest: DeleteProductMaterialRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteProductMaterialRequest' is not null or undefined
            assertParamExists('deleteProductMaterials', 'deleteProductMaterialRequest', deleteProductMaterialRequest)
            const localVarPath = `/admin/api/v1/products/materials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteProductMaterialRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readProductColors: async (productId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('readProductColors', 'productId', productId)
            const localVarPath = `/admin/api/v1/products/colors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (productId !== undefined) {
                localVarQueryParameter['productId'] = productId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readProductImages: async (productId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('readProductImages', 'productId', productId)
            const localVarPath = `/admin/api/v1/products/images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (productId !== undefined) {
                localVarQueryParameter['productId'] = productId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readProductMaterials: async (productId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('readProductMaterials', 'productId', productId)
            const localVarPath = `/admin/api/v1/products/materials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (productId !== undefined) {
                localVarQueryParameter['productId'] = productId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ReadProductsProductTypeEnum} [productType] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readProducts: async (productType?: ReadProductsProductTypeEnum, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/api/v1/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (productType !== undefined) {
                localVarQueryParameter['productType'] = productType;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SaveProductRequest} saveProductRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveProduct: async (saveProductRequest: SaveProductRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'saveProductRequest' is not null or undefined
            assertParamExists('saveProduct', 'saveProductRequest', saveProductRequest)
            const localVarPath = `/admin/api/v1/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(saveProductRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SaveProductColorRequest} saveProductColorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveProductColors: async (saveProductColorRequest: SaveProductColorRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'saveProductColorRequest' is not null or undefined
            assertParamExists('saveProductColors', 'saveProductColorRequest', saveProductColorRequest)
            const localVarPath = `/admin/api/v1/products/colors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(saveProductColorRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SaveProductImageRequest} saveProductImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveProductImages: async (saveProductImageRequest: SaveProductImageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'saveProductImageRequest' is not null or undefined
            assertParamExists('saveProductImages', 'saveProductImageRequest', saveProductImageRequest)
            const localVarPath = `/admin/api/v1/products/images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(saveProductImageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SaveProductMaterialRequest} saveProductMaterialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveProductMaterials: async (saveProductMaterialRequest: SaveProductMaterialRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'saveProductMaterialRequest' is not null or undefined
            assertParamExists('saveProductMaterials', 'saveProductMaterialRequest', saveProductMaterialRequest)
            const localVarPath = `/admin/api/v1/products/materials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(saveProductMaterialRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateProductRequest} updateProductRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProduct: async (updateProductRequest: UpdateProductRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateProductRequest' is not null or undefined
            assertParamExists('updateProduct', 'updateProductRequest', updateProductRequest)
            const localVarPath = `/admin/api/v1/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateProductRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ChangePrimaryProductImageRequest} changePrimaryProductImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePrimaryImageOfProduct(changePrimaryProductImageRequest: ChangePrimaryProductImageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePrimaryImageOfProduct(changePrimaryProductImageRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.changePrimaryImageOfProduct']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPreSignedUrl(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseGetPreSignedUrlResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPreSignedUrl(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.createPreSignedUrl']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {DeleteProductColorRequest} deleteProductColorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProductColors(deleteProductColorRequest: DeleteProductColorRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProductColors(deleteProductColorRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.deleteProductColors']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {DeleteProductImageRequest} deleteProductImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProductImages(deleteProductImageRequest: DeleteProductImageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProductImages(deleteProductImageRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.deleteProductImages']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {DeleteProductMaterialRequest} deleteProductMaterialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProductMaterials(deleteProductMaterialRequest: DeleteProductMaterialRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProductMaterials(deleteProductMaterialRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.deleteProductMaterials']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readProductColors(productId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListProductColorResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readProductColors(productId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.readProductColors']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readProductImages(productId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListProductImageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readProductImages(productId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.readProductImages']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readProductMaterials(productId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListProductMaterialResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readProductMaterials(productId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.readProductMaterials']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {ReadProductsProductTypeEnum} [productType] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readProducts(productType?: ReadProductsProductTypeEnum, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListProductResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readProducts(productType, page, size, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.readProducts']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {SaveProductRequest} saveProductRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveProduct(saveProductRequest: SaveProductRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveProduct(saveProductRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.saveProduct']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {SaveProductColorRequest} saveProductColorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveProductColors(saveProductColorRequest: SaveProductColorRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveProductColors(saveProductColorRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.saveProductColors']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {SaveProductImageRequest} saveProductImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveProductImages(saveProductImageRequest: SaveProductImageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveProductImages(saveProductImageRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.saveProductImages']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {SaveProductMaterialRequest} saveProductMaterialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveProductMaterials(saveProductMaterialRequest: SaveProductMaterialRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveProductMaterials(saveProductMaterialRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.saveProductMaterials']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateProductRequest} updateProductRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProduct(updateProductRequest: UpdateProductRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProduct(updateProductRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.updateProduct']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {ChangePrimaryProductImageRequest} changePrimaryProductImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePrimaryImageOfProduct(changePrimaryProductImageRequest: ChangePrimaryProductImageRequest, options?: any): AxiosPromise<ApiResponseLong> {
            return localVarFp.changePrimaryImageOfProduct(changePrimaryProductImageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPreSignedUrl(options?: any): AxiosPromise<ApiResponseGetPreSignedUrlResponse> {
            return localVarFp.createPreSignedUrl(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DeleteProductColorRequest} deleteProductColorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProductColors(deleteProductColorRequest: DeleteProductColorRequest, options?: any): AxiosPromise<ApiResponseBoolean> {
            return localVarFp.deleteProductColors(deleteProductColorRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DeleteProductImageRequest} deleteProductImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProductImages(deleteProductImageRequest: DeleteProductImageRequest, options?: any): AxiosPromise<ApiResponseBoolean> {
            return localVarFp.deleteProductImages(deleteProductImageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DeleteProductMaterialRequest} deleteProductMaterialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProductMaterials(deleteProductMaterialRequest: DeleteProductMaterialRequest, options?: any): AxiosPromise<ApiResponseBoolean> {
            return localVarFp.deleteProductMaterials(deleteProductMaterialRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readProductColors(productId: number, options?: any): AxiosPromise<ApiResponseListProductColorResponse> {
            return localVarFp.readProductColors(productId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readProductImages(productId: number, options?: any): AxiosPromise<ApiResponseListProductImageResponse> {
            return localVarFp.readProductImages(productId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} productId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readProductMaterials(productId: number, options?: any): AxiosPromise<ApiResponseListProductMaterialResponse> {
            return localVarFp.readProductMaterials(productId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ReadProductsProductTypeEnum} [productType] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readProducts(productType?: ReadProductsProductTypeEnum, page?: number, size?: number, options?: any): AxiosPromise<ApiResponseListProductResponse> {
            return localVarFp.readProducts(productType, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SaveProductRequest} saveProductRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveProduct(saveProductRequest: SaveProductRequest, options?: any): AxiosPromise<ApiResponseLong> {
            return localVarFp.saveProduct(saveProductRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SaveProductColorRequest} saveProductColorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveProductColors(saveProductColorRequest: SaveProductColorRequest, options?: any): AxiosPromise<ApiResponseListLong> {
            return localVarFp.saveProductColors(saveProductColorRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SaveProductImageRequest} saveProductImageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveProductImages(saveProductImageRequest: SaveProductImageRequest, options?: any): AxiosPromise<ApiResponseListLong> {
            return localVarFp.saveProductImages(saveProductImageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SaveProductMaterialRequest} saveProductMaterialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveProductMaterials(saveProductMaterialRequest: SaveProductMaterialRequest, options?: any): AxiosPromise<ApiResponseListLong> {
            return localVarFp.saveProductMaterials(saveProductMaterialRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateProductRequest} updateProductRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProduct(updateProductRequest: UpdateProductRequest, options?: any): AxiosPromise<ApiResponseLong> {
            return localVarFp.updateProduct(updateProductRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {ChangePrimaryProductImageRequest} changePrimaryProductImageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public changePrimaryImageOfProduct(changePrimaryProductImageRequest: ChangePrimaryProductImageRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).changePrimaryImageOfProduct(changePrimaryProductImageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createPreSignedUrl(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createPreSignedUrl(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DeleteProductColorRequest} deleteProductColorRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteProductColors(deleteProductColorRequest: DeleteProductColorRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteProductColors(deleteProductColorRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DeleteProductImageRequest} deleteProductImageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteProductImages(deleteProductImageRequest: DeleteProductImageRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteProductImages(deleteProductImageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DeleteProductMaterialRequest} deleteProductMaterialRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteProductMaterials(deleteProductMaterialRequest: DeleteProductMaterialRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteProductMaterials(deleteProductMaterialRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readProductColors(productId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).readProductColors(productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readProductImages(productId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).readProductImages(productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readProductMaterials(productId: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).readProductMaterials(productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ReadProductsProductTypeEnum} [productType] 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readProducts(productType?: ReadProductsProductTypeEnum, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).readProducts(productType, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SaveProductRequest} saveProductRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public saveProduct(saveProductRequest: SaveProductRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).saveProduct(saveProductRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SaveProductColorRequest} saveProductColorRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public saveProductColors(saveProductColorRequest: SaveProductColorRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).saveProductColors(saveProductColorRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SaveProductImageRequest} saveProductImageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public saveProductImages(saveProductImageRequest: SaveProductImageRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).saveProductImages(saveProductImageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SaveProductMaterialRequest} saveProductMaterialRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public saveProductMaterials(saveProductMaterialRequest: SaveProductMaterialRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).saveProductMaterials(saveProductMaterialRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateProductRequest} updateProductRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateProduct(updateProductRequest: UpdateProductRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateProduct(updateProductRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ReadProductsProductTypeEnum = {
    Ring: 'RING',
    Necklace: 'NECKLACE',
    Earring: 'EARRING',
    Bracelet: 'BRACELET',
    Base: 'BASE'
} as const;
export type ReadProductsProductTypeEnum = typeof ReadProductsProductTypeEnum[keyof typeof ReadProductsProductTypeEnum];


